
- hosts: servers
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.alertmanager
  vars_files:
    - extra.yaml  
  vars:
    alertmanager_version: latest
    alertmanager_smtp:
      smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
      from: 'alerts@gmail.com'
      auth_username: ''
      auth_password: ''
      require_tls: true    
    alertmanager_slack_api_url: "https://hooks.slack.com/services/"
    alertmanager_receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            channel: '#devops_terraform'
    alertmanager_route:
      receiver: slack
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
      - match:
          team: DBA
        receiver: dba_email     
